---
- hosts: switches
  gather_facts: no
  connection: local

 tasks:
  - name: CONFIGURE LOOPBACK INTERFACE
    ios_config:
      lines:
        - description Core Router LOOPBACK
        - ipv4 address 10.1.1.1 255.255.255.255
      parents: interface FastEthernet0/1
