---
- hosts: switches
  become: yes
  become_method: enable
  gather_facts: no
  connection: local


################################################################################
#
# Step 2.1: Define task to configure the Loopback0 interface.
#
################################################################################

  tasks:
  - name: CONFIGURE LOOPBACK INTERFACE
    ios_config:
      lines:
        - description Core Router LOOPBACK
        - ip address 10.1.1.1 255.255.255.255
      parents: interface FastEthernet0/1
